trigger:
  branches:
    include:
      - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

jobs:
- job: x32_ABI
  pool:
    vmImage: ubuntu-18.04
  steps:
    - script: './setup_linux.sh'
    - script: './build_tor.sh i686-linux-android 19 i686 x86 x86'
    - script: './build_tor.sh arm-linux-androideabi  19 armv7 arm-linux-androideabi arm'
    - script: './build_tor.sh aarch64-linux-android  21 armv8 aarch64-linux-android arm64'
    - script: './build_tor.sh x86_64-linux-android  21 x86-64 x86_64-linux-android x86_64'
    - script: './deploy_linux.sh $(Build.BuildNumber) $(UPLOADCREDS)'
  displayName: 'build Tor for Android'
